/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as privateIndexImport } from './routes/(private)/index'
import { Route as publicGridLayoutImport } from './routes/(public)/_grid-layout'
import { Route as privateWorkspaceidImport } from './routes/(private)/$workspace_id'
import { Route as publicGridLayoutServerActivationImport } from './routes/(public)/_grid-layout/server-activation'
import { Route as publicGridLayoutLoginImport } from './routes/(public)/_grid-layout/login'
import { Route as privateWorkspaceidComponentsIndexImport } from './routes/(private)/$workspace_id/components/index'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()
const privateWorkspaceidIndexLazyImport = createFileRoute(
  '/(private)/$workspace_id/',
)()
const privateWorkspaceidComponentsCreateLazyImport = createFileRoute(
  '/(private)/$workspace_id/components/create',
)()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  getParentRoute: () => rootRoute,
} as any)

const privateIndexRoute = privateIndexImport.update({
  id: '/(private)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const publicGridLayoutRoute = publicGridLayoutImport.update({
  id: '/_grid-layout',
  getParentRoute: () => publicRoute,
} as any)

const privateWorkspaceidRoute = privateWorkspaceidImport
  .update({
    id: '/(private)/$workspace_id',
    path: '/$workspace_id',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(private)/$workspace_id.lazy').then((d) => d.Route),
  )

const privateWorkspaceidIndexLazyRoute = privateWorkspaceidIndexLazyImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => privateWorkspaceidRoute,
  } as any)
  .lazy(() =>
    import('./routes/(private)/$workspace_id/index.lazy').then((d) => d.Route),
  )

const publicGridLayoutServerActivationRoute =
  publicGridLayoutServerActivationImport
    .update({
      id: '/server-activation',
      path: '/server-activation',
      getParentRoute: () => publicGridLayoutRoute,
    } as any)
    .lazy(() =>
      import('./routes/(public)/_grid-layout/server-activation.lazy').then(
        (d) => d.Route,
      ),
    )

const publicGridLayoutLoginRoute = publicGridLayoutLoginImport
  .update({
    id: '/login',
    path: '/login',
    getParentRoute: () => publicGridLayoutRoute,
  } as any)
  .lazy(() =>
    import('./routes/(public)/_grid-layout/login.lazy').then((d) => d.Route),
  )

const privateWorkspaceidComponentsIndexRoute =
  privateWorkspaceidComponentsIndexImport
    .update({
      id: '/components/',
      path: '/components/',
      getParentRoute: () => privateWorkspaceidRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$workspace_id/components/index.lazy').then(
        (d) => d.Route,
      ),
    )

const privateWorkspaceidComponentsCreateLazyRoute =
  privateWorkspaceidComponentsCreateLazyImport
    .update({
      id: '/components/create',
      path: '/components/create',
      getParentRoute: () => privateWorkspaceidRoute,
    } as any)
    .lazy(() =>
      import('./routes/(private)/$workspace_id/components/create.lazy').then(
        (d) => d.Route,
      ),
    )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)/$workspace_id': {
      id: '/(private)/$workspace_id'
      path: '/$workspace_id'
      fullPath: '/$workspace_id'
      preLoaderRoute: typeof privateWorkspaceidImport
      parentRoute: typeof rootRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_grid-layout': {
      id: '/(public)/_grid-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicGridLayoutImport
      parentRoute: typeof publicRoute
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_grid-layout/login': {
      id: '/(public)/_grid-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicGridLayoutLoginImport
      parentRoute: typeof publicGridLayoutImport
    }
    '/(public)/_grid-layout/server-activation': {
      id: '/(public)/_grid-layout/server-activation'
      path: '/server-activation'
      fullPath: '/server-activation'
      preLoaderRoute: typeof publicGridLayoutServerActivationImport
      parentRoute: typeof publicGridLayoutImport
    }
    '/(private)/$workspace_id/': {
      id: '/(private)/$workspace_id/'
      path: '/'
      fullPath: '/$workspace_id/'
      preLoaderRoute: typeof privateWorkspaceidIndexLazyImport
      parentRoute: typeof privateWorkspaceidImport
    }
    '/(private)/$workspace_id/components/create': {
      id: '/(private)/$workspace_id/components/create'
      path: '/components/create'
      fullPath: '/$workspace_id/components/create'
      preLoaderRoute: typeof privateWorkspaceidComponentsCreateLazyImport
      parentRoute: typeof privateWorkspaceidImport
    }
    '/(private)/$workspace_id/components/': {
      id: '/(private)/$workspace_id/components/'
      path: '/components'
      fullPath: '/$workspace_id/components'
      preLoaderRoute: typeof privateWorkspaceidComponentsIndexImport
      parentRoute: typeof privateWorkspaceidImport
    }
  }
}

// Create and export the route tree

interface privateWorkspaceidRouteChildren {
  privateWorkspaceidIndexLazyRoute: typeof privateWorkspaceidIndexLazyRoute
  privateWorkspaceidComponentsCreateLazyRoute: typeof privateWorkspaceidComponentsCreateLazyRoute
  privateWorkspaceidComponentsIndexRoute: typeof privateWorkspaceidComponentsIndexRoute
}

const privateWorkspaceidRouteChildren: privateWorkspaceidRouteChildren = {
  privateWorkspaceidIndexLazyRoute: privateWorkspaceidIndexLazyRoute,
  privateWorkspaceidComponentsCreateLazyRoute:
    privateWorkspaceidComponentsCreateLazyRoute,
  privateWorkspaceidComponentsIndexRoute:
    privateWorkspaceidComponentsIndexRoute,
}

const privateWorkspaceidRouteWithChildren =
  privateWorkspaceidRoute._addFileChildren(privateWorkspaceidRouteChildren)

interface publicGridLayoutRouteChildren {
  publicGridLayoutLoginRoute: typeof publicGridLayoutLoginRoute
  publicGridLayoutServerActivationRoute: typeof publicGridLayoutServerActivationRoute
}

const publicGridLayoutRouteChildren: publicGridLayoutRouteChildren = {
  publicGridLayoutLoginRoute: publicGridLayoutLoginRoute,
  publicGridLayoutServerActivationRoute: publicGridLayoutServerActivationRoute,
}

const publicGridLayoutRouteWithChildren =
  publicGridLayoutRoute._addFileChildren(publicGridLayoutRouteChildren)

interface publicRouteChildren {
  publicGridLayoutRoute: typeof publicGridLayoutRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicGridLayoutRoute: publicGridLayoutRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/$workspace_id': typeof privateWorkspaceidRouteWithChildren
  '/': typeof privateIndexRoute
  '/login': typeof publicGridLayoutLoginRoute
  '/server-activation': typeof publicGridLayoutServerActivationRoute
  '/$workspace_id/': typeof privateWorkspaceidIndexLazyRoute
  '/$workspace_id/components/create': typeof privateWorkspaceidComponentsCreateLazyRoute
  '/$workspace_id/components': typeof privateWorkspaceidComponentsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof privateIndexRoute
  '/login': typeof publicGridLayoutLoginRoute
  '/server-activation': typeof publicGridLayoutServerActivationRoute
  '/$workspace_id': typeof privateWorkspaceidIndexLazyRoute
  '/$workspace_id/components/create': typeof privateWorkspaceidComponentsCreateLazyRoute
  '/$workspace_id/components': typeof privateWorkspaceidComponentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(private)/$workspace_id': typeof privateWorkspaceidRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_grid-layout': typeof publicGridLayoutRouteWithChildren
  '/(private)/': typeof privateIndexRoute
  '/(public)/_grid-layout/login': typeof publicGridLayoutLoginRoute
  '/(public)/_grid-layout/server-activation': typeof publicGridLayoutServerActivationRoute
  '/(private)/$workspace_id/': typeof privateWorkspaceidIndexLazyRoute
  '/(private)/$workspace_id/components/create': typeof privateWorkspaceidComponentsCreateLazyRoute
  '/(private)/$workspace_id/components/': typeof privateWorkspaceidComponentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$workspace_id'
    | '/'
    | '/login'
    | '/server-activation'
    | '/$workspace_id/'
    | '/$workspace_id/components/create'
    | '/$workspace_id/components'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/server-activation'
    | '/$workspace_id'
    | '/$workspace_id/components/create'
    | '/$workspace_id/components'
  id:
    | '__root__'
    | '/(private)/$workspace_id'
    | '/(public)'
    | '/(public)/_grid-layout'
    | '/(private)/'
    | '/(public)/_grid-layout/login'
    | '/(public)/_grid-layout/server-activation'
    | '/(private)/$workspace_id/'
    | '/(private)/$workspace_id/components/create'
    | '/(private)/$workspace_id/components/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  privateWorkspaceidRoute: typeof privateWorkspaceidRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
  privateIndexRoute: typeof privateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  privateWorkspaceidRoute: privateWorkspaceidRouteWithChildren,
  publicRoute: publicRouteWithChildren,
  privateIndexRoute: privateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(private)/$workspace_id",
        "/(public)",
        "/(private)/"
      ]
    },
    "/(private)/$workspace_id": {
      "filePath": "(private)/$workspace_id.tsx",
      "children": [
        "/(private)/$workspace_id/",
        "/(private)/$workspace_id/components/create",
        "/(private)/$workspace_id/components/"
      ]
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/_grid-layout"
      ]
    },
    "/(public)/_grid-layout": {
      "filePath": "(public)/_grid-layout.tsx",
      "parent": "/(public)",
      "children": [
        "/(public)/_grid-layout/login",
        "/(public)/_grid-layout/server-activation"
      ]
    },
    "/(private)/": {
      "filePath": "(private)/index.tsx"
    },
    "/(public)/_grid-layout/login": {
      "filePath": "(public)/_grid-layout/login.tsx",
      "parent": "/(public)/_grid-layout"
    },
    "/(public)/_grid-layout/server-activation": {
      "filePath": "(public)/_grid-layout/server-activation.tsx",
      "parent": "/(public)/_grid-layout"
    },
    "/(private)/$workspace_id/": {
      "filePath": "(private)/$workspace_id/index.lazy.tsx",
      "parent": "/(private)/$workspace_id"
    },
    "/(private)/$workspace_id/components/create": {
      "filePath": "(private)/$workspace_id/components/create.lazy.tsx",
      "parent": "/(private)/$workspace_id"
    },
    "/(private)/$workspace_id/components/": {
      "filePath": "(private)/$workspace_id/components/index.tsx",
      "parent": "/(private)/$workspace_id"
    }
  }
}
ROUTE_MANIFEST_END */
