/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as privateIndexRouteImport } from './routes/(private)/index'
import { Route as publicGridLayoutRouteRouteImport } from './routes/(public)/_grid-layout/route'
import { Route as privateSidebarRouteRouteImport } from './routes/(private)/_sidebar/route'
import { Route as publicGridLayoutServerActivationRouteImport } from './routes/(public)/_grid-layout/server-activation'
import { Route as publicGridLayoutLoginRouteImport } from './routes/(public)/_grid-layout/login'
import { Route as privateSidebarStacksRouteRouteImport } from './routes/(private)/_sidebar/stacks/route'
import { Route as privateSidebarSettingsRouteRouteImport } from './routes/(private)/_sidebar/settings/route'
import { Route as privateSidebarProjectsRouteRouteImport } from './routes/(private)/_sidebar/projects/route'
import { Route as privateSidebarComponentsRouteRouteImport } from './routes/(private)/_sidebar/components/route'
import { Route as privateSidebarStacksIndexRouteImport } from './routes/(private)/_sidebar/stacks/index'
import { Route as privateSidebarSettingsIndexRouteImport } from './routes/(private)/_sidebar/settings/index'
import { Route as privateSidebarProjectsIndexRouteImport } from './routes/(private)/_sidebar/projects/index'
import { Route as privateSidebarComponentsIndexRouteImport } from './routes/(private)/_sidebar/components/index'
import { Route as privateSidebarSettingsSecretsRouteImport } from './routes/(private)/_sidebar/settings/secrets'
import { Route as privateSidebarSettingsMembersRouteImport } from './routes/(private)/_sidebar/settings/members'
import { Route as privateSidebarSettingsGeneralRouteImport } from './routes/(private)/_sidebar/settings/general'
import { Route as privateSidebarProjectsProject_idRouteImport } from './routes/(private)/_sidebar/projects/$project_id'
import { Route as privateSidebarComponentsComponent_idRouteRouteImport } from './routes/(private)/_sidebar/components/$component_id/route'
import { Route as privateSidebarComponentsComponent_idIndexRouteImport } from './routes/(private)/_sidebar/components/$component_id/index'
import { Route as privateSidebarComponentsComponent_idStacksRouteImport } from './routes/(private)/_sidebar/components/$component_id/stacks'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateRouteRoute,
} as any)
const publicGridLayoutRouteRoute = publicGridLayoutRouteRouteImport.update({
  id: '/(public)/_grid-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const privateSidebarRouteRoute = privateSidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => privateRouteRoute,
} as any)
const publicGridLayoutServerActivationRoute =
  publicGridLayoutServerActivationRouteImport.update({
    id: '/server-activation',
    path: '/server-activation',
    getParentRoute: () => publicGridLayoutRouteRoute,
  } as any)
const publicGridLayoutLoginRoute = publicGridLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicGridLayoutRouteRoute,
} as any)
const privateSidebarStacksRouteRoute =
  privateSidebarStacksRouteRouteImport.update({
    id: '/stacks',
    path: '/stacks',
    getParentRoute: () => privateSidebarRouteRoute,
  } as any)
const privateSidebarSettingsRouteRoute =
  privateSidebarSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => privateSidebarRouteRoute,
  } as any)
const privateSidebarProjectsRouteRoute =
  privateSidebarProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => privateSidebarRouteRoute,
  } as any)
const privateSidebarComponentsRouteRoute =
  privateSidebarComponentsRouteRouteImport.update({
    id: '/components',
    path: '/components',
    getParentRoute: () => privateSidebarRouteRoute,
  } as any)
const privateSidebarStacksIndexRoute =
  privateSidebarStacksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateSidebarStacksRouteRoute,
  } as any)
const privateSidebarSettingsIndexRoute =
  privateSidebarSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateSidebarSettingsRouteRoute,
  } as any)
const privateSidebarProjectsIndexRoute =
  privateSidebarProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateSidebarProjectsRouteRoute,
  } as any)
const privateSidebarComponentsIndexRoute =
  privateSidebarComponentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateSidebarComponentsRouteRoute,
  } as any)
const privateSidebarSettingsSecretsRoute =
  privateSidebarSettingsSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => privateSidebarSettingsRouteRoute,
  } as any)
const privateSidebarSettingsMembersRoute =
  privateSidebarSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => privateSidebarSettingsRouteRoute,
  } as any)
const privateSidebarSettingsGeneralRoute =
  privateSidebarSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => privateSidebarSettingsRouteRoute,
  } as any)
const privateSidebarProjectsProject_idRoute =
  privateSidebarProjectsProject_idRouteImport.update({
    id: '/$project_id',
    path: '/$project_id',
    getParentRoute: () => privateSidebarProjectsRouteRoute,
  } as any)
const privateSidebarComponentsComponent_idRouteRoute =
  privateSidebarComponentsComponent_idRouteRouteImport.update({
    id: '/$component_id',
    path: '/$component_id',
    getParentRoute: () => privateSidebarComponentsRouteRoute,
  } as any)
const privateSidebarComponentsComponent_idIndexRoute =
  privateSidebarComponentsComponent_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateSidebarComponentsComponent_idRouteRoute,
  } as any)
const privateSidebarComponentsComponent_idStacksRoute =
  privateSidebarComponentsComponent_idStacksRouteImport.update({
    id: '/stacks',
    path: '/stacks',
    getParentRoute: () => privateSidebarComponentsComponent_idRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof privateIndexRoute
  '/components': typeof privateSidebarComponentsRouteRouteWithChildren
  '/projects': typeof privateSidebarProjectsRouteRouteWithChildren
  '/settings': typeof privateSidebarSettingsRouteRouteWithChildren
  '/stacks': typeof privateSidebarStacksRouteRouteWithChildren
  '/login': typeof publicGridLayoutLoginRoute
  '/server-activation': typeof publicGridLayoutServerActivationRoute
  '/components/$component_id': typeof privateSidebarComponentsComponent_idRouteRouteWithChildren
  '/projects/$project_id': typeof privateSidebarProjectsProject_idRoute
  '/settings/general': typeof privateSidebarSettingsGeneralRoute
  '/settings/members': typeof privateSidebarSettingsMembersRoute
  '/settings/secrets': typeof privateSidebarSettingsSecretsRoute
  '/components/': typeof privateSidebarComponentsIndexRoute
  '/projects/': typeof privateSidebarProjectsIndexRoute
  '/settings/': typeof privateSidebarSettingsIndexRoute
  '/stacks/': typeof privateSidebarStacksIndexRoute
  '/components/$component_id/stacks': typeof privateSidebarComponentsComponent_idStacksRoute
  '/components/$component_id/': typeof privateSidebarComponentsComponent_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof privateIndexRoute
  '/login': typeof publicGridLayoutLoginRoute
  '/server-activation': typeof publicGridLayoutServerActivationRoute
  '/projects/$project_id': typeof privateSidebarProjectsProject_idRoute
  '/settings/general': typeof privateSidebarSettingsGeneralRoute
  '/settings/members': typeof privateSidebarSettingsMembersRoute
  '/settings/secrets': typeof privateSidebarSettingsSecretsRoute
  '/components': typeof privateSidebarComponentsIndexRoute
  '/projects': typeof privateSidebarProjectsIndexRoute
  '/settings': typeof privateSidebarSettingsIndexRoute
  '/stacks': typeof privateSidebarStacksIndexRoute
  '/components/$component_id/stacks': typeof privateSidebarComponentsComponent_idStacksRoute
  '/components/$component_id': typeof privateSidebarComponentsComponent_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/_sidebar': typeof privateSidebarRouteRouteWithChildren
  '/(public)/_grid-layout': typeof publicGridLayoutRouteRouteWithChildren
  '/(private)/': typeof privateIndexRoute
  '/(private)/_sidebar/components': typeof privateSidebarComponentsRouteRouteWithChildren
  '/(private)/_sidebar/projects': typeof privateSidebarProjectsRouteRouteWithChildren
  '/(private)/_sidebar/settings': typeof privateSidebarSettingsRouteRouteWithChildren
  '/(private)/_sidebar/stacks': typeof privateSidebarStacksRouteRouteWithChildren
  '/(public)/_grid-layout/login': typeof publicGridLayoutLoginRoute
  '/(public)/_grid-layout/server-activation': typeof publicGridLayoutServerActivationRoute
  '/(private)/_sidebar/components/$component_id': typeof privateSidebarComponentsComponent_idRouteRouteWithChildren
  '/(private)/_sidebar/projects/$project_id': typeof privateSidebarProjectsProject_idRoute
  '/(private)/_sidebar/settings/general': typeof privateSidebarSettingsGeneralRoute
  '/(private)/_sidebar/settings/members': typeof privateSidebarSettingsMembersRoute
  '/(private)/_sidebar/settings/secrets': typeof privateSidebarSettingsSecretsRoute
  '/(private)/_sidebar/components/': typeof privateSidebarComponentsIndexRoute
  '/(private)/_sidebar/projects/': typeof privateSidebarProjectsIndexRoute
  '/(private)/_sidebar/settings/': typeof privateSidebarSettingsIndexRoute
  '/(private)/_sidebar/stacks/': typeof privateSidebarStacksIndexRoute
  '/(private)/_sidebar/components/$component_id/stacks': typeof privateSidebarComponentsComponent_idStacksRoute
  '/(private)/_sidebar/components/$component_id/': typeof privateSidebarComponentsComponent_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/projects'
    | '/settings'
    | '/stacks'
    | '/login'
    | '/server-activation'
    | '/components/$component_id'
    | '/projects/$project_id'
    | '/settings/general'
    | '/settings/members'
    | '/settings/secrets'
    | '/components/'
    | '/projects/'
    | '/settings/'
    | '/stacks/'
    | '/components/$component_id/stacks'
    | '/components/$component_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/server-activation'
    | '/projects/$project_id'
    | '/settings/general'
    | '/settings/members'
    | '/settings/secrets'
    | '/components'
    | '/projects'
    | '/settings'
    | '/stacks'
    | '/components/$component_id/stacks'
    | '/components/$component_id'
  id:
    | '__root__'
    | '/(private)'
    | '/(private)/_sidebar'
    | '/(public)/_grid-layout'
    | '/(private)/'
    | '/(private)/_sidebar/components'
    | '/(private)/_sidebar/projects'
    | '/(private)/_sidebar/settings'
    | '/(private)/_sidebar/stacks'
    | '/(public)/_grid-layout/login'
    | '/(public)/_grid-layout/server-activation'
    | '/(private)/_sidebar/components/$component_id'
    | '/(private)/_sidebar/projects/$project_id'
    | '/(private)/_sidebar/settings/general'
    | '/(private)/_sidebar/settings/members'
    | '/(private)/_sidebar/settings/secrets'
    | '/(private)/_sidebar/components/'
    | '/(private)/_sidebar/projects/'
    | '/(private)/_sidebar/settings/'
    | '/(private)/_sidebar/stacks/'
    | '/(private)/_sidebar/components/$component_id/stacks'
    | '/(private)/_sidebar/components/$component_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicGridLayoutRouteRoute: typeof publicGridLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/_grid-layout': {
      id: '/(public)/_grid-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicGridLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_sidebar': {
      id: '/(private)/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateSidebarRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/_grid-layout/server-activation': {
      id: '/(public)/_grid-layout/server-activation'
      path: '/server-activation'
      fullPath: '/server-activation'
      preLoaderRoute: typeof publicGridLayoutServerActivationRouteImport
      parentRoute: typeof publicGridLayoutRouteRoute
    }
    '/(public)/_grid-layout/login': {
      id: '/(public)/_grid-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicGridLayoutLoginRouteImport
      parentRoute: typeof publicGridLayoutRouteRoute
    }
    '/(private)/_sidebar/stacks': {
      id: '/(private)/_sidebar/stacks'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof privateSidebarStacksRouteRouteImport
      parentRoute: typeof privateSidebarRouteRoute
    }
    '/(private)/_sidebar/settings': {
      id: '/(private)/_sidebar/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privateSidebarSettingsRouteRouteImport
      parentRoute: typeof privateSidebarRouteRoute
    }
    '/(private)/_sidebar/projects': {
      id: '/(private)/_sidebar/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof privateSidebarProjectsRouteRouteImport
      parentRoute: typeof privateSidebarRouteRoute
    }
    '/(private)/_sidebar/components': {
      id: '/(private)/_sidebar/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof privateSidebarComponentsRouteRouteImport
      parentRoute: typeof privateSidebarRouteRoute
    }
    '/(private)/_sidebar/stacks/': {
      id: '/(private)/_sidebar/stacks/'
      path: '/'
      fullPath: '/stacks/'
      preLoaderRoute: typeof privateSidebarStacksIndexRouteImport
      parentRoute: typeof privateSidebarStacksRouteRoute
    }
    '/(private)/_sidebar/settings/': {
      id: '/(private)/_sidebar/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof privateSidebarSettingsIndexRouteImport
      parentRoute: typeof privateSidebarSettingsRouteRoute
    }
    '/(private)/_sidebar/projects/': {
      id: '/(private)/_sidebar/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof privateSidebarProjectsIndexRouteImport
      parentRoute: typeof privateSidebarProjectsRouteRoute
    }
    '/(private)/_sidebar/components/': {
      id: '/(private)/_sidebar/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof privateSidebarComponentsIndexRouteImport
      parentRoute: typeof privateSidebarComponentsRouteRoute
    }
    '/(private)/_sidebar/settings/secrets': {
      id: '/(private)/_sidebar/settings/secrets'
      path: '/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof privateSidebarSettingsSecretsRouteImport
      parentRoute: typeof privateSidebarSettingsRouteRoute
    }
    '/(private)/_sidebar/settings/members': {
      id: '/(private)/_sidebar/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof privateSidebarSettingsMembersRouteImport
      parentRoute: typeof privateSidebarSettingsRouteRoute
    }
    '/(private)/_sidebar/settings/general': {
      id: '/(private)/_sidebar/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof privateSidebarSettingsGeneralRouteImport
      parentRoute: typeof privateSidebarSettingsRouteRoute
    }
    '/(private)/_sidebar/projects/$project_id': {
      id: '/(private)/_sidebar/projects/$project_id'
      path: '/$project_id'
      fullPath: '/projects/$project_id'
      preLoaderRoute: typeof privateSidebarProjectsProject_idRouteImport
      parentRoute: typeof privateSidebarProjectsRouteRoute
    }
    '/(private)/_sidebar/components/$component_id': {
      id: '/(private)/_sidebar/components/$component_id'
      path: '/$component_id'
      fullPath: '/components/$component_id'
      preLoaderRoute: typeof privateSidebarComponentsComponent_idRouteRouteImport
      parentRoute: typeof privateSidebarComponentsRouteRoute
    }
    '/(private)/_sidebar/components/$component_id/': {
      id: '/(private)/_sidebar/components/$component_id/'
      path: '/'
      fullPath: '/components/$component_id/'
      preLoaderRoute: typeof privateSidebarComponentsComponent_idIndexRouteImport
      parentRoute: typeof privateSidebarComponentsComponent_idRouteRoute
    }
    '/(private)/_sidebar/components/$component_id/stacks': {
      id: '/(private)/_sidebar/components/$component_id/stacks'
      path: '/stacks'
      fullPath: '/components/$component_id/stacks'
      preLoaderRoute: typeof privateSidebarComponentsComponent_idStacksRouteImport
      parentRoute: typeof privateSidebarComponentsComponent_idRouteRoute
    }
  }
}

interface privateSidebarComponentsComponent_idRouteRouteChildren {
  privateSidebarComponentsComponent_idStacksRoute: typeof privateSidebarComponentsComponent_idStacksRoute
  privateSidebarComponentsComponent_idIndexRoute: typeof privateSidebarComponentsComponent_idIndexRoute
}

const privateSidebarComponentsComponent_idRouteRouteChildren: privateSidebarComponentsComponent_idRouteRouteChildren =
  {
    privateSidebarComponentsComponent_idStacksRoute:
      privateSidebarComponentsComponent_idStacksRoute,
    privateSidebarComponentsComponent_idIndexRoute:
      privateSidebarComponentsComponent_idIndexRoute,
  }

const privateSidebarComponentsComponent_idRouteRouteWithChildren =
  privateSidebarComponentsComponent_idRouteRoute._addFileChildren(
    privateSidebarComponentsComponent_idRouteRouteChildren,
  )

interface privateSidebarComponentsRouteRouteChildren {
  privateSidebarComponentsComponent_idRouteRoute: typeof privateSidebarComponentsComponent_idRouteRouteWithChildren
  privateSidebarComponentsIndexRoute: typeof privateSidebarComponentsIndexRoute
}

const privateSidebarComponentsRouteRouteChildren: privateSidebarComponentsRouteRouteChildren =
  {
    privateSidebarComponentsComponent_idRouteRoute:
      privateSidebarComponentsComponent_idRouteRouteWithChildren,
    privateSidebarComponentsIndexRoute: privateSidebarComponentsIndexRoute,
  }

const privateSidebarComponentsRouteRouteWithChildren =
  privateSidebarComponentsRouteRoute._addFileChildren(
    privateSidebarComponentsRouteRouteChildren,
  )

interface privateSidebarProjectsRouteRouteChildren {
  privateSidebarProjectsProject_idRoute: typeof privateSidebarProjectsProject_idRoute
  privateSidebarProjectsIndexRoute: typeof privateSidebarProjectsIndexRoute
}

const privateSidebarProjectsRouteRouteChildren: privateSidebarProjectsRouteRouteChildren =
  {
    privateSidebarProjectsProject_idRoute:
      privateSidebarProjectsProject_idRoute,
    privateSidebarProjectsIndexRoute: privateSidebarProjectsIndexRoute,
  }

const privateSidebarProjectsRouteRouteWithChildren =
  privateSidebarProjectsRouteRoute._addFileChildren(
    privateSidebarProjectsRouteRouteChildren,
  )

interface privateSidebarSettingsRouteRouteChildren {
  privateSidebarSettingsGeneralRoute: typeof privateSidebarSettingsGeneralRoute
  privateSidebarSettingsMembersRoute: typeof privateSidebarSettingsMembersRoute
  privateSidebarSettingsSecretsRoute: typeof privateSidebarSettingsSecretsRoute
  privateSidebarSettingsIndexRoute: typeof privateSidebarSettingsIndexRoute
}

const privateSidebarSettingsRouteRouteChildren: privateSidebarSettingsRouteRouteChildren =
  {
    privateSidebarSettingsGeneralRoute: privateSidebarSettingsGeneralRoute,
    privateSidebarSettingsMembersRoute: privateSidebarSettingsMembersRoute,
    privateSidebarSettingsSecretsRoute: privateSidebarSettingsSecretsRoute,
    privateSidebarSettingsIndexRoute: privateSidebarSettingsIndexRoute,
  }

const privateSidebarSettingsRouteRouteWithChildren =
  privateSidebarSettingsRouteRoute._addFileChildren(
    privateSidebarSettingsRouteRouteChildren,
  )

interface privateSidebarStacksRouteRouteChildren {
  privateSidebarStacksIndexRoute: typeof privateSidebarStacksIndexRoute
}

const privateSidebarStacksRouteRouteChildren: privateSidebarStacksRouteRouteChildren =
  {
    privateSidebarStacksIndexRoute: privateSidebarStacksIndexRoute,
  }

const privateSidebarStacksRouteRouteWithChildren =
  privateSidebarStacksRouteRoute._addFileChildren(
    privateSidebarStacksRouteRouteChildren,
  )

interface privateSidebarRouteRouteChildren {
  privateSidebarComponentsRouteRoute: typeof privateSidebarComponentsRouteRouteWithChildren
  privateSidebarProjectsRouteRoute: typeof privateSidebarProjectsRouteRouteWithChildren
  privateSidebarSettingsRouteRoute: typeof privateSidebarSettingsRouteRouteWithChildren
  privateSidebarStacksRouteRoute: typeof privateSidebarStacksRouteRouteWithChildren
}

const privateSidebarRouteRouteChildren: privateSidebarRouteRouteChildren = {
  privateSidebarComponentsRouteRoute:
    privateSidebarComponentsRouteRouteWithChildren,
  privateSidebarProjectsRouteRoute:
    privateSidebarProjectsRouteRouteWithChildren,
  privateSidebarSettingsRouteRoute:
    privateSidebarSettingsRouteRouteWithChildren,
  privateSidebarStacksRouteRoute: privateSidebarStacksRouteRouteWithChildren,
}

const privateSidebarRouteRouteWithChildren =
  privateSidebarRouteRoute._addFileChildren(privateSidebarRouteRouteChildren)

interface privateRouteRouteChildren {
  privateSidebarRouteRoute: typeof privateSidebarRouteRouteWithChildren
  privateIndexRoute: typeof privateIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateSidebarRouteRoute: privateSidebarRouteRouteWithChildren,
  privateIndexRoute: privateIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicGridLayoutRouteRouteChildren {
  publicGridLayoutLoginRoute: typeof publicGridLayoutLoginRoute
  publicGridLayoutServerActivationRoute: typeof publicGridLayoutServerActivationRoute
}

const publicGridLayoutRouteRouteChildren: publicGridLayoutRouteRouteChildren = {
  publicGridLayoutLoginRoute: publicGridLayoutLoginRoute,
  publicGridLayoutServerActivationRoute: publicGridLayoutServerActivationRoute,
}

const publicGridLayoutRouteRouteWithChildren =
  publicGridLayoutRouteRoute._addFileChildren(
    publicGridLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicGridLayoutRouteRoute: publicGridLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
